version: "3.8"

services:
  backend:
    image: ${APP_NAME_BACKEND}:${APP_VERSION}
    ports:
      - ${BROADCAST_PORT_BACKEND:-8080}:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

volumes:
  postgres_data:
  
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.44.15/24