version: "3.8"

services:
  backend:
    command: gunicorn -b 0.0.0.0:8000 -w 3 -k gevent shop_project.wsgi:application
    image: ${APP_NAME_BACKEND}:${APP_VERSION}
    volumes:
      - static_volume:/home/docker/app/staticfiles
    ports:
      - ${BROADCAST_PORT_BACKEND:-8000}:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - ${BROADCAST_PORT_NGINX:-8080}:80
    depends_on:
      - backend
volumes:
  postgres_data:
  static_volume:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.44.15/24